feat: added email update funcionality
SaaammmyyyS/CS_Elective pull request #76
Opened 2024-05-01 17:23 UTC by RonBers

-Updated profile view to display current user info -Implemented a tab navigation for the profile view -Implemented the email update

2024-05-03 06:36 UTC, RonBers commented
Added the confirmation dialog

2024-05-04 20:15 UTC, SaaammmyyyS requested changes

2024-05-04 20:15 UTC, SaaammmyyyS commented on frontend/src/widgets/layout/usersettings.jsx
> +import ConfirmDialog from "../ui/confirmation";
delete unused import

2024-05-04 21:25 UTC, RonBers commented on frontend/src/widgets/layout/usersettings.jsx
> +import ConfirmDialog from "../ui/confirmation";
done in the latest commit

2024-05-04 21:43 UTC, SaaammmyyyS approved these changes

2024-05-04 22:04 UTC, merged